# CMake generated Testfile for 
# Source directory: /host/ubuntudata/code/publish/leveldb
# Build directory: /host/ubuntudata/code/publish/leveldb
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(c_test "/host/ubuntudata/code/publish/leveldb/c_test")
add_test(fault_injection_test "/host/ubuntudata/code/publish/leveldb/fault_injection_test")
add_test(issue178_test "/host/ubuntudata/code/publish/leveldb/issue178_test")
add_test(issue200_test "/host/ubuntudata/code/publish/leveldb/issue200_test")
add_test(env_test "/host/ubuntudata/code/publish/leveldb/env_test")
add_test(status_test "/host/ubuntudata/code/publish/leveldb/status_test")
add_test(no_destructor_test "/host/ubuntudata/code/publish/leveldb/no_destructor_test")
add_test(autocompact_test "/host/ubuntudata/code/publish/leveldb/autocompact_test")
add_test(corruption_test "/host/ubuntudata/code/publish/leveldb/corruption_test")
add_test(db_test "/host/ubuntudata/code/publish/leveldb/db_test")
add_test(dbformat_test "/host/ubuntudata/code/publish/leveldb/dbformat_test")
add_test(filename_test "/host/ubuntudata/code/publish/leveldb/filename_test")
add_test(log_test "/host/ubuntudata/code/publish/leveldb/log_test")
add_test(recovery_test "/host/ubuntudata/code/publish/leveldb/recovery_test")
add_test(skiplist_test "/host/ubuntudata/code/publish/leveldb/skiplist_test")
add_test(version_edit_test "/host/ubuntudata/code/publish/leveldb/version_edit_test")
add_test(version_set_test "/host/ubuntudata/code/publish/leveldb/version_set_test")
add_test(write_batch_test "/host/ubuntudata/code/publish/leveldb/write_batch_test")
add_test(memenv_test "/host/ubuntudata/code/publish/leveldb/memenv_test")
add_test(filter_block_test "/host/ubuntudata/code/publish/leveldb/filter_block_test")
add_test(table_test "/host/ubuntudata/code/publish/leveldb/table_test")
add_test(arena_test "/host/ubuntudata/code/publish/leveldb/arena_test")
add_test(bloom_test "/host/ubuntudata/code/publish/leveldb/bloom_test")
add_test(cache_test "/host/ubuntudata/code/publish/leveldb/cache_test")
add_test(coding_test "/host/ubuntudata/code/publish/leveldb/coding_test")
add_test(crc32c_test "/host/ubuntudata/code/publish/leveldb/crc32c_test")
add_test(hash_test "/host/ubuntudata/code/publish/leveldb/hash_test")
add_test(logging_test "/host/ubuntudata/code/publish/leveldb/logging_test")
add_test(env_posix_test "/host/ubuntudata/code/publish/leveldb/env_posix_test")
